[env:rak4631_debug]
platform = nordicnrf52
platform_packages =
  framework-arduinoadafruitnrf52 @ 1.10700.0
board = rak4631
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
build_flags =
  -w
  -I/tmp/MeshCore/variants/rak4631
build_src_filter =
  +<*.cpp>
  +</tmp/MeshCore/variants/rak4631/variant.cpp>
